version: "3.3"

services:
  records:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    links:
      - records-datadog-agent
