name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir tmp
          cd tmp
          curl -fsSL https://github.com/lukeshay/deployer/releases/download/v0.0.1/deployer-linux-x86_64.tar.gz --output deployer.tar.gz
          tar -xzvf deployer.tar.gz
      - name: Dagger
        uses: dagger/dagger-for-github@v5
        env:
          GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}
        with:
          verb: run
          args: ./tmp/deployer docker build --docker-username actions --repo lukeshay/deployer --ref main --tags "main,latest,$GITHUB_SHA" --publish --local
  deploy:
    needs:
      - build
    runs-on: ubuntu-22.04
    environment:
      name: prod
      url: https://ls-records.fly.dev/
    steps:
      - uses: actions/checkout@v4
      - run: docker pull ghcr.io/lukeshay/deployer:$GITHUB_SHA
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --image ghcr.io/lukeshay/deployer:$GITHUB_SHA
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
