name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: curl https://raw.githubusercontent.com/lukeshay/deployer/main/install.sh | bash
      - uses: dagger/dagger-for-github@v5
        with:
          args: ./deployer/deployer dagger docker build --username "${{ github.actor }}" --password "${{ secrets.GHCR_PASSWORD }}" --repository "ghcr.io/lukeshay/records" --tags "main,latest,main-$GITHUB_SHA,$GITHUB_SHA" --labels "org.opencontainers.image.revision=$GITHUB_SHA" --pull ghcr.io/lukeshay/records:main --publish
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          verb: run
  deploy:
    needs:
      - build
    runs-on: ubuntu-22.04
    environment:
      name: prod
      url: https://ls-records.fly.dev/
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: docker pull ghcr.io/lukeshay/records:$GITHUB_SHA
      - run: flyctl deploy --image ghcr.io/lukeshay/records:$GITHUB_SHA
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
